# Generated by Django 3.2.12 on 2024-03-07 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientsforrecipe',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='menu.ingredient'),
            preserve_default=False,
        ),
    ]
